### ISSUE TITLE
[Enhancement] Add support for querying agent state by org and device

### ISSUE THREAD

**Issue by ceciliastevens** [code42/py42#161]
## Summary
Code42 has APIs that allow the querying of agent state by guid and by org ID. Py42 should allow these to be called and returned in the way we do for other APIs.

Swagger documentation can be found here: 

* https://console.us.code42.com/swagger/index.html?urls.primaryName=v14#/agent-state/AgentState_ViewByDeviceGuid
* https://console.us.code42.com/swagger/index.html?urls.primaryName=v14#/agent-state/AgentState_ViewByOrganizationId

## Proposed API

```
sdk.devices.get_agent_state("guid",["example key 1", "example key 2"])
sdk.orgs.get_agent_state("orgId",["example key 1", "example key 2"])
```

## Intended Use Case
Administrators can quickly and easily determine the health or other parameters of agents in their environments.

**Comment by alanag13** [comment]
@ceciliastevens thanks for submitting this -- I have a couple of suggestions / questions here:

- is there a list of known keys? If we could provide the as constants in the code that seems like it could be beneficial.
- The API only allows you to retrieve on key at a time -- for consistency's sake we want ever py42 function that calls APIs to return a `Py42Response`, so we would probably make this function mirror the api in that. You could, of course, pretty easily implement your own function that looped over a list of key and called this for each item.

**Comment by ceciliastevens** [comment]
> @ceciliastevens thanks for submitting this! I have a couple of suggestions / questions here:
> 
> * is there a list of known keys? If we could provide them as constants in the code that seems like it could be beneficial.

I am not aware of a list of keys maintained anywhere. The only one I know of is `fullDiskAccess`

> * The API only allows you to retrieve one key at a time -- for consistency's sake we want every py42 function that calls APIs to return a `Py42Response`, so we would probably make this function mirror the api in that way. You could, of course, pretty easily implement your own function that looped over a list of key and called this for each item.

Ah, I misread the API documentation. I'm working on an implementation now, I'll update it to only accept the one key.

**Comment by ceciliastevens** [comment]
Looking at the database, it appears that currently fullDiskAccess is the only agent state property available. Do you recommend leaving the method open to other properties should they be added down the line, or should we have the method automatically query full disk access for now?

**Comment by alanag13** [comment]
@ceciliastevens we could do both, if you're up for it. By that I mean that we could have a convenience function written just for `fullDiskAccess` that just calls your proposal behind the scenes. The advantage of this is that if new keys are added, the api will still be accessible without us having add new convenience functions, as long as you had the key. We would, of course, aim to eventually make convenience functions for all known keys, but this way you get some convenience and are also not blocked if you ever need to look up a newly-added key.

**Comment by ceciliastevens** [comment]
I like that idea! So we'll end up with:

```
sdk.devices.get_agent_state("guid","fullDiskAccess")
sdk.orgs.get_agent_state("orgId","fullDiskAccess")
sdk.devices.check_full_disk_access("guid")
sdk.orgs.check_full_disk_access("orgId")
```

Does that sound good?

**Comment by alanag13** [comment]
re: naming, rather than `check_full_disk_access`, I would be a little more descriptive on what the function does/returns, probably something like `get_agent_full_disk_access_state()` (probably `states` for org)

But otherwise I think we're on the same page 👍
