### ISSUE TITLE
[Enhancement] Py42UnableToDeactivateError

### ISSUE THREAD

**Issue by unparalleled-js** [code42/py42#169]
## Summary
A custom exception for when trying to block a user who is on legalhold

## Proposed API

The `py42.users.deactivate()` and `py42.devices.deactivate()` APIs

## Intended Use Case
Call `users.deactivate()` on a user who is a legal hold custodian should raise a specific error reflected that state.

**Comment by DiscoRiver** [comment]
I'll look at this one.
