### ISSUE TITLE
Allow query filter values to be flexible on format

### ISSUE THREAD

**Issue by unparalleled-js** [code42/py42#171]
## Summary
Consider the `FileCategory` query filter which can take the term `SOURCE_CODE` as a value. However, on alert-query responses where there is a nested object named `observations`, the file category has the term `SourceCode`.... To go from one to the other, you have to do an unfortunate mapping. Should we burden our users with this mapping?

Btw, I realize this is simply inconsistent behavior with our APIs and that is the root of the problem.

## Proposed API

No API, just behind the scenes mapping.

## Intended Use Case

Here is an example of what it might look like:
```
value = observation["fileCategories"][0]["category"]
_filter = FileCategory.eq(value)
```

**Comment by alanag13** [comment]
If i remember right, this is something that the ffs team was actually aware of and I think they planned to make it so that either format for the category names would work, but I haven't tried that myself. If that's the case, we should probably switch the constants to the new format for best future-proofing.

**Comment by unparalleled-js** [comment]
> If i remember right, this is something that the ffs team was actually aware of and I think they planned to make it so that either format for the category names would work, but I'm not sure whether or not that change was ever actually made and I haven't tried that myself. If that's the case, we should probably switch the constants to the new format for best future-proofing.

It does not seem to work, at least with the APIs py42 calls.  I get bad request when using `SourceCode` as the value
