### ISSUE TITLE
[Bug] pg_size and pg_num have no effect in the saved search execute method

### ISSUE THREAD

**Issue by unparalleled-js** [code42/py42#179]
### Description

The `execute()` method for saved searches is not doing anything with `pg_num` or `pg_size`.

### Steps to Reproduce

1. Try using `pg_num` or `pg_size` on a saved search `execute()` call.
2. In debug mode, notice that the default params are always in the request
3. Also, look at the code and see that they are not used.

### Expected Behavior
To be able to use the `pg_size` and `pg_num` parameters when executing a saved search

### Actual Behavior
The default values for the query are always used.

**Comment by DiscoRiver** [comment]
I can take this on.

**Comment by DiscoRiver** [comment]
@unparalleled-js - Should we update `execute()` so that it returns a generator, or are we relying on the user to supply `pg_num` and `pg_size`?

If it's the latter, do we just document that the user needs to handle the inevitable 400 error themselves, indicating they've reached the end?

```
Py42BadRequestError: Failure in HTTP call 400 Client Error: Bad Request for url: https://forensicsearch-east.us.code42.com/forensic-search/queryservice/api/v1/fileevent
```
