### ISSUE TITLE
[Bug] AlertRulesService.add_user fails when user has never been on a detection list

### ISSUE THREAD

**Issue by alanag13** [code42/py42#185]
### Description

`AlertRulesService.add_user()` fails when user has never been on a detection list.

This is because the detection list user profile service is used to try to determine the aliases for the user to be submitted, and the user will not have a detection list user profile if they have never been on a detection list (or had a profile created manually via the api).
https://github.com/code42/py42/blob/d7434bf9d073041ed269da558e4e731f04b34a96/src/py42/services/alertrules.py#L44

### Steps to Reproduce

1. call `sdk.alerts.rules.add_user()` with a user that has no detection list profile (perhaps verifying this using a user that was just created).

### Expected Behavior
The user should be added to the alert rule with an empty list of aliases.

### Actual Behavior
The action fails and raises a `Py42BadRequestError` on the line linked to above.

**Comment by alanag13** [comment]
suggested solution: catch `Py42BadRequestError` on the problem line and continue as normal with an empty list for `user_aliases`.

**Comment by unparalleled-js** [comment]
We should also get rid of `create_if_not_exists()` and just rely on creating the profile when checking the ID.
