### ISSUE TITLE
[Bug] Cannot set pgNum or pgSize for FileEventQuery() 

### ISSUE THREAD

**Issue by themullinator** [code42/py42#202]
Similar to #179, I cannot find a way to set a non-default pgNum or pgSize when calling `sdk.securitydata.search_file_events()`

## Steps to Reproduce
Example Script:
```
#!/usr/bin/python3
import py42.sdk
import py42.settings as settings
from py42.sdk.queries.fileevents.file_event_query import FileEventQuery
from py42.sdk.queries.fileevents.filters import *

settings.security_events_per_page = 25

sdk = py42.sdk.from_local_account(
    "console_url",
    "username",
    "password"
)

time_filter = EventTimestamp.within_the_last(EventTimestamp.FIFTEEN_MINUTES)
query = FileEventQuery.all(time_filter)

print(query)
```

## Expected Results
```
{
  "groupClause":"AND",
  "groups":[{"filterClause":"AND", "filters":[{"operator":"WITHIN_THE_LAST", "term":"eventTimestamp", "value":"PT15M"}]}],
  "pgNum":1, 
  "pgSize":25, 
  "srtDir":"asc", 
  "srtKey":"eventId"
}
```

## Actual Results
```
{
  "groupClause":"AND",
   "groups":[{"filterClause":"AND", "filters":[{"operator":"WITHIN_THE_LAST", "term":"eventTimestamp", "value":"PT15M"}]}], 
  "pgNum":1, 
  "pgSize":10000, 
  "srtDir":"asc", 
  "srtKey":"eventId"
}
```

I've also tried passing `page_number=2` as a kwarg when instantiating a new FileEventQuery, but that doesn't seem to have any effect either.

**Comment by DiscoRiver** [comment]
@themullinator - Thanks for reporting this. 

It was fixed in #179, however hasn't gone into a release yet. If you're using a version installed with pip, you may not yet have this fix.

I've tested this using the script you've provided, based on the current master branch, and I'm getting the expected output.

**Comment by alanag13** [comment]
@themullinator per @DiscoRiver's statement, `security_events_per_page` has not been released yet (but should be soon)!

In the mean time, you can still change the default page size by setting the `page_size` property of the `FileEventQuery` object:

```python
import py42.settings as settings
from py42.sdk.queries.fileevents.file_event_query import FileEventQuery
from py42.sdk.queries.fileevents.filters import *
time_filter = EventTimestamp.within_the_last(EventTimestamp.FIFTEEN_MINUTES)
query = FileEventQuery.all(time_filter)
query.page_size = 42 # set the page size desired here
print(query)
```
yields

```
{
  "groupClause": "AND",
  "groups": [
    {
      "filterClause": "AND",
      "filters": [
        {
          "operator": "WITHIN_THE_LAST",
          "term": "eventTimestamp",
          "value": "PT15M"
        }
      ]
    }
  ],
  "pgNum": 1,
  "pgSize": 42,
  "srtDir": "asc",
  "srtKey": "eventId"
}
```

**Comment by alanag13** [comment]
I'm noticing that our documentation and examples do not make the existence of that property very apparent -- I'll make a note to add something there to make this more obvious.

**Comment by alanag13** [comment]
@themullinator it looks like @DiscoRiver was actually correct in his statement that this hasn't been released yet -- there must have been a merge conflict in our CHANGELOG that was incorrectly resolved, giving the appearance that this feature was released when it hasn't been :-/. I was able to reproduce your porblem on the latest release.

That being said, I can also confirm that your reproduction steps work as expected in the master branch, so this should be resolved in our next release. Until then, you can use the workaround above.

current release: https://github.com/code42/py42/blob/5b693c5cc206c42db5786a5e26696fb372b3f0c0/src/py42/sdk/queries/__init__.py#L8

master:
https://github.com/code42/py42/blob/38de5e8e1628fffa4189036ffe73405d41c62c33/src/py42/sdk/queries/__init__.py#L10

**Comment by themullinator** [comment]
Confirmed, the workaround solves the problem for me in version 1.8.1 :) Thanks for the super fast response!
