### ISSUE TITLE
[Bug] Changelog incorrectly reporting that some unreleased items have been released

### ISSUE THREAD

**Issue by alanag13** [code42/py42#203]
### Description
#179 has not been released but is being reported in the CHANGELOG as released in 1.8.0.

### Steps to Reproduce

1. View Changelog
2. See that `security_events_per_page` is reported as released

### Expected Behavior
This item (and other changes tied to the same PR) should be in the `Unreleased` section of the changelog. We should check the set of commits since the latest release and confirm there aren't any other cases of this.

**Comment by DiscoRiver** [comment]
This one is on me. I'll update it.
