### ISSUE TITLE
[Enhancement] UserAlreadyExistsError for users.create_user()

### ISSUE THREAD

**Issue by unparalleled-js** [code42/py42#214]
## Summary
We should create a new custom exception, such as `UserAlreadyExistsError`, and raise it during `sdk.users.create_user()`. When a user already exists in Code42, the backend sends a 500 error with the body containing 'USER_DUPLICATE' (thanks @kiran-chaudhary for pointing this out).

## Proposed API

`py42.exceptions.UserAlreadyExistsError`

## Intended Use Case
This way, if we someone is automating creating users and from a list, and the same user happens to be on the list more than once, they can more easily catch this exception and skip it or handle it how they choose.

**Comment by adilanchian** [comment]
Hey @unparalleled-js !

I have a change ready to PR for this, but will most likely add it later today :)

I did have a few question though:
1. Is it valid to actually check `error_response.response.text` for `USER_DUPLICATE` or does this come back somewhere deeper in an error object or something?
2. I wrote a new test for this, but wasn't able to actually see it run using tox? Am I missing something here?

Thanks!

**Comment by alanag13** [comment]
hi @adilanchian ! Happy to hear you're thinking about contributing. To answer your questions:
1. As long as we also check for a 500-series status code, checking for that text string is fine. That approach is essentially what is followed here: https://github.com/code42/py42/blob/4fe4ba56006a2ca2b2676e3d47084591223f87e8/src/py42/exceptions.py#L158

2. Without seeing what you've written I can't think of an obvious reason why you wouldn't see your test run, but if you open a PR we'd be happy to advise you about any changes that should be made to get everything aligned correctly!

**Comment by adilanchian** [comment]
Thanks for the reply!

Ya looking through the tests that are running, I actually didn't know any I've the services tests in there? So wondering if they are just not showing up in terminal or something!

Either way, PR coming soon :). Thanks!
