### ISSUE TITLE
[Enhancement] Support Rate Limit Throttling 

### ISSUE THREAD

**Issue by csanders-git** [code42/py42#225]
## Summary
Per [Code 42 Documentation](https://support.code42.com/Administrator/Cloud/Monitoring_and_managing/Code42_API_resources/Forensic_Search_API#:~:text=Request%20rate%3A%20To%20ensure%20optimal,requests%20to%20120%20per%20minute.), there is a limit on API requests that can be made. That request is fairly low and as a result folks are likely to run into it. This will result in `py42.exceptions.Py42HTTPError: Failure in HTTP call 429 Client Error: Too Many Requests for url`. 

## Proposed API

The easiest way to fix this would be to make a specific exception for rate limits so those could be easily caught, of course the more elegant solution is to allow a configurable rate limit and back off parameter. 

## Intended Use Case
Supporting automation using the API.

**Comment by alanag13** [comment]
@csanders-git thanks for the suggestion! I agree that a custom exception is the least we could do here.

**Comment by alanag13** [comment]
The custom exception `Py42TooManyRequestsError` has been added now, but we could still consider a back-off implementation in the future.
