### ISSUE TITLE
[Enhancement] Add support for nextPgToken

### ISSUE THREAD

**Issue by csanders-git** [code42/py42#227]
## Summary
It seems possible enough to use `query.page_num` to interact with queries of a size < 10,000. Per the documentation the API is supposed to return a nextPgToken if the request has over 10,000 results (Although this doesn't seem to be working in production yet as I continue to get responses with "nextPgToken":null). The documentation indicates that "A pgToken is the only way to page past 10,000 results. 

The documentation states the following: "If pgToken is supplied, pgNum is ignored. Provide empty string to retrieve the 'first page of results and null to use the pgNum value. Default is null." (https://forensicsearch-east.us.code42.com/forensic-search/queryservice/swagger-ui.html#/file-event-controller) .  

## Proposed API

add a self.page_token value in BaseQuery (https://github.com/code42/py42/blob/52abb32bdd397edbcf5824fbf0b2cf155b1128ce/src/py42/sdk/queries/__init__.py#L5) such that it can be overwritten in a similar manner to query.page_num. When pgToken is in use set pgNum to null. Ensure that resulting post request for example (https://github.com/code42/py42/blob/765dee58c90b4e53ea224e95c7d4662193243e62/src/py42/services/fileevent.py#L26) is generated to include pgToken when value is not default (otherwise it should not be included).

## Intended Use Case
Support querying of search_file_events for export to ELK. Even on a minute by minute basis that the cron job will fire at, this may have more than 10,000 events with a moderately sized deploy. It would be best if there was a method whereby these could automatically be pushed to an S3 bucket to prevent taxing the API.

As a note, it seems this approach cannot scale to over 120,000 events per minute, this seems to be a limitation of the product.

**Comment by alanag13** [comment]
hi @csanders-git , interestingly my team originally requested this feature, it just isn't yet implemented in py42 yet, but is already on our roadmap. The feature does work in production, but it appears to not be well documented.

I was thinking that we could implement this as a generator like we do with some of the other methods for paging. We could make managing the pgToken / nextPageToken transparent to the user.

**Comment by csanders-git** [comment]
@alanag13 so the generator idea is nice, the only problem being that without rate limiting support this can easily just break. 
If you're willing to accept a PR I could probably put it together (if i can get it to work)
I'm surprised to hear it works, It doesn't seem to be working on our account see the following request reporting 56641 total events, with only one event shown and no page token provided.

<img width="1153" alt="Screen Shot 2020-11-17 at 10 48 01 AM" src="https://user-images.githubusercontent.com/4632287/99433777-ce9b9000-28c2-11eb-93ee-5762be24e45f.png">

<img width="1343" alt="Screen Shot 2020-11-17 at 10 49 21 AM" src="https://user-images.githubusercontent.com/4632287/99433779-cfccbd00-28c2-11eb-970e-455328732402.png">

**Comment by alanag13** [comment]
@csanders-git we're definitely willing to accept PRs! 

If you don't get around to it, that's okay -- we were planning on look at both this and #225 in the near future. You raise a very good point about how rate limiting could interfere with the generator. I'm thinking the path of least resistance / easiest implementation to get what you're after would then be something like:
- add version of file event search function that return a tuple of `nextPageToken, results` and `accepts a pageToken`.
- raise new exception type for 429 errors

This would allow you to catch the 429 whenever it occurs and then use your own "back-off and retry" logic.

As for the API itself, you need to omit the `pgNum` argument and supply a `pgToken` of `""`. This should cause a populated `nextPgToken` to be returned, which you would supply as the `pgToken` of the subsequent request (the query must remain unchanged). Repeat this process until you get a `nextPgToken` of `null`, which would indicate the end of the result set.
