### ISSUE TITLE
[Bug] sdk.devices.get_settings fails if there is a single locked destination

### ISSUE THREAD

**Issue by ceciliastevens** [code42/py42#248]
### Description

when running `sdk.devices.get_settings()`, I encountered a stacktrace thrown by ../py42/clients/settings/device_settings.py, line 357. 

### Steps to Reproduce

1. Create a device in Code42.
2. Assign the device a single, locked, destination
3. Attempt to retrieve the device's settings using py42

### Expected Behavior
The settings data retrieves and parses correctly.

### Actual Behavior
My device has this `destinations` object in its settings JSON:

```
              "destinations": {
                "@locked": "true",
                "destination": {
                  "@id": "632540230984925185",
                  "@locked": "true"
                }
```

py42 is attempting to process it like this:

```
for d in self.data[u"destinations"]:
            guid = d[u"@id"]
            dest_name = self._manager.available_destinations[guid]
            if u"@locked" in d:
                dest_name = dest_name + u" <LOCKED>"
            destination_dict[guid] = dest_name
```

This throws a stack trace because `d[u"@id"]` does not exist; since self.data[u"destinations"] is a dict and not a list.

### Basic Information

- py42 version: 1.10.0
- python version: 3.7.4
- operating system: Mac OS 10.15.7

**Comment by timabrmsn** [comment]
So it looks like this happens because the device is on legal hold, as you can't actually lock "destinations" overall in the backup config (or org device defaults) settings. You can lock individual destinations, but here the lock is on all destinations.
