### ISSUE TITLE
[Enhancement] "Unable to find org" Error for Devices GetAll

### ISSUE THREAD

**Issue by unparalleled-js** [code42/py42#273]
## Summary
A custom exception raised when specifying `orgUid` when getting all devices and you get a 400 bad request with response content containing: `"Unable to find org"`.

## Proposed API

```
class DeviceOrgNotExistsError(BadRequest)
```

## Intended Use Case
This way, in the Code42 CLI, we can more-easily catch this and print a helpful message

**Comment by timabrmsn** [comment]
Fixed in 1.18.1
